/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAriaSearchRouteImport } from './routes/api/aria/search'
import { Route as ApiAriaRunsRouteImport } from './routes/api/aria/runs'
import { Route as ApiAriaDeliveriesRouteImport } from './routes/api/aria/deliveries'
import { Route as ApiAriaRunsIdRouteImport } from './routes/api/aria/runs.$id'
import { Route as ApiAriaRunsIdEventsRouteImport } from './routes/api/aria/runs.$id.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAriaSearchRoute = ApiAriaSearchRouteImport.update({
  id: '/api/aria/search',
  path: '/api/aria/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAriaRunsRoute = ApiAriaRunsRouteImport.update({
  id: '/api/aria/runs',
  path: '/api/aria/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAriaDeliveriesRoute = ApiAriaDeliveriesRouteImport.update({
  id: '/api/aria/deliveries',
  path: '/api/aria/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAriaRunsIdRoute = ApiAriaRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAriaRunsRoute,
} as any)
const ApiAriaRunsIdEventsRoute = ApiAriaRunsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiAriaRunsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/aria/deliveries': typeof ApiAriaDeliveriesRoute
  '/api/aria/runs': typeof ApiAriaRunsRouteWithChildren
  '/api/aria/search': typeof ApiAriaSearchRoute
  '/api/aria/runs/$id': typeof ApiAriaRunsIdRouteWithChildren
  '/api/aria/runs/$id/events': typeof ApiAriaRunsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/aria/deliveries': typeof ApiAriaDeliveriesRoute
  '/api/aria/runs': typeof ApiAriaRunsRouteWithChildren
  '/api/aria/search': typeof ApiAriaSearchRoute
  '/api/aria/runs/$id': typeof ApiAriaRunsIdRouteWithChildren
  '/api/aria/runs/$id/events': typeof ApiAriaRunsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/aria/deliveries': typeof ApiAriaDeliveriesRoute
  '/api/aria/runs': typeof ApiAriaRunsRouteWithChildren
  '/api/aria/search': typeof ApiAriaSearchRoute
  '/api/aria/runs/$id': typeof ApiAriaRunsIdRouteWithChildren
  '/api/aria/runs/$id/events': typeof ApiAriaRunsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/aria/deliveries'
    | '/api/aria/runs'
    | '/api/aria/search'
    | '/api/aria/runs/$id'
    | '/api/aria/runs/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/aria/deliveries'
    | '/api/aria/runs'
    | '/api/aria/search'
    | '/api/aria/runs/$id'
    | '/api/aria/runs/$id/events'
  id:
    | '__root__'
    | '/'
    | '/api/aria/deliveries'
    | '/api/aria/runs'
    | '/api/aria/search'
    | '/api/aria/runs/$id'
    | '/api/aria/runs/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAriaDeliveriesRoute: typeof ApiAriaDeliveriesRoute
  ApiAriaRunsRoute: typeof ApiAriaRunsRouteWithChildren
  ApiAriaSearchRoute: typeof ApiAriaSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aria/search': {
      id: '/api/aria/search'
      path: '/api/aria/search'
      fullPath: '/api/aria/search'
      preLoaderRoute: typeof ApiAriaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aria/runs': {
      id: '/api/aria/runs'
      path: '/api/aria/runs'
      fullPath: '/api/aria/runs'
      preLoaderRoute: typeof ApiAriaRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aria/deliveries': {
      id: '/api/aria/deliveries'
      path: '/api/aria/deliveries'
      fullPath: '/api/aria/deliveries'
      preLoaderRoute: typeof ApiAriaDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aria/runs/$id': {
      id: '/api/aria/runs/$id'
      path: '/$id'
      fullPath: '/api/aria/runs/$id'
      preLoaderRoute: typeof ApiAriaRunsIdRouteImport
      parentRoute: typeof ApiAriaRunsRoute
    }
    '/api/aria/runs/$id/events': {
      id: '/api/aria/runs/$id/events'
      path: '/events'
      fullPath: '/api/aria/runs/$id/events'
      preLoaderRoute: typeof ApiAriaRunsIdEventsRouteImport
      parentRoute: typeof ApiAriaRunsIdRoute
    }
  }
}

interface ApiAriaRunsIdRouteChildren {
  ApiAriaRunsIdEventsRoute: typeof ApiAriaRunsIdEventsRoute
}

const ApiAriaRunsIdRouteChildren: ApiAriaRunsIdRouteChildren = {
  ApiAriaRunsIdEventsRoute: ApiAriaRunsIdEventsRoute,
}

const ApiAriaRunsIdRouteWithChildren = ApiAriaRunsIdRoute._addFileChildren(
  ApiAriaRunsIdRouteChildren,
)

interface ApiAriaRunsRouteChildren {
  ApiAriaRunsIdRoute: typeof ApiAriaRunsIdRouteWithChildren
}

const ApiAriaRunsRouteChildren: ApiAriaRunsRouteChildren = {
  ApiAriaRunsIdRoute: ApiAriaRunsIdRouteWithChildren,
}

const ApiAriaRunsRouteWithChildren = ApiAriaRunsRoute._addFileChildren(
  ApiAriaRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAriaDeliveriesRoute: ApiAriaDeliveriesRoute,
  ApiAriaRunsRoute: ApiAriaRunsRouteWithChildren,
  ApiAriaSearchRoute: ApiAriaSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
